name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # ajuste para o nome da sua branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@users.noreply.github.com'
          echo "www.seudominio.com" > ./build/CNAME  # opcional: para personalizar o domínio
          git add ./build
          git commit -m "Deploy to GitHub Pages"
          git push -f origin HEAD:gh-pages

