name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # ajuste para o nome da sua branch principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # ajuste para a versão do Node.js usada no seu projeto

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@users.noreply.github.com'
          echo "www.seudominio.com" > ./build/CNAME  # opcional: para personalizar o domínio
          git checkout --orphan gh-pages
          git --no-verify add ./build
          git --no-verify commit -m "Deploying to GitHub Pages from Action"
          git push --force --quiet "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" gh-pages:${{ github.ref }}

